import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { CATEGORIES, type CategoryKey } from './categories';
import { slugifyHeading } from './slug';

const BLOG_DIR = path.join(process.cwd(), 'content/blog');
const PUBLIC_DIR = path.join(process.cwd(), 'public');

// Average adult silent reading speed, used only to round to a friendly
// "N min read" label — not a claim of precision.
const WORDS_PER_MINUTE = 200;

export type ArticleStatus = 'published' | 'review';

export type BlogFrontmatter = {
  title: string;
  /** Meta description, also the visible excerpt under the H1. */
  description: string;
  /** Optional shorter/longer <title> when the H1 isn't the best search title. */
  seoTitle?: string;
  date: string; // YYYY-MM-DD
  /** Optional: set only when a post is materially revised after publishing. */
  updated?: string; // YYYY-MM-DD
  tags: string[];
  /** Defaults to 'astrology' — every post written before the ecosystem was. */
  category?: CategoryKey;
  /**
   * 'review' posts render only in dev and on preview deployments (with a
   * banner and noindex) until a human reviewer publishes them. Defaults to
   * 'published' so the pre-existing posts need no change.
   */
  status?: ArticleStatus;
  reviewedBy?: string;
  reviewedAt?: string; // YYYY-MM-DD
  faqs?: { question: string; answer: string }[];
  /**
   * Public path to the hero image. Optional: by convention the hero lives
   * at /assets/blog/<category>/<slug>.webp (generated by
   * scripts/blog-art/generate.mjs from `art` below).
   */
  hero?: string;
  heroAlt?: string;
  /** Input for the hero generator — see scripts/blog-art/README.md. */
  art?: { motif: string; focus?: string | number | (string | number)[] };
  author?: string;
  /** Hand-picked related slugs, shown before the computed ones. */
  related?: string[];
  /** Aroha feature keys this article naturally connects to (see FEATURE_LINKS). */
  features?: string[];
  /** Surfaced on the homepage knowledge section and hub pages. */
  featured?: boolean;
  /** Further reading shown under the article; plain references, not endorsements. */
  sources?: { title: string; url?: string; note?: string }[];
};

export type Heading = { depth: 2 | 3; text: string; id: string };

export type BlogPost = {
  slug: string;
  frontmatter: BlogFrontmatter;
  category: CategoryKey;
  status: ArticleStatus;
  hero: string | null;
  content: string;
  /** Rounded minutes to read `content`, derived from its word count. */
  readingTime: number;
  headings: Heading[];
  isPillar: boolean;
};

/**
 * Whether unreviewed ('review') articles are visible in this build: always
 * in local dev, on Vercel preview deployments (where the reviewer reads
 * them), or when explicitly forced. Never on a production deployment.
 */
export const SHOW_REVIEW_CONTENT =
  process.env.NODE_ENV === 'development' ||
  process.env.VERCEL_ENV === 'preview' ||
  process.env.AROHA_SHOW_REVIEW === '1';

export { slugifyHeading };

function plainHeadingText(raw: string): string {
  return raw
    .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
    .replace(/[`*_~]/g, '')
    .trim();
}

function extractHeadings(content: string): Heading[] {
  const out: Heading[] = [];
  let inFence = false;
  for (const line of content.split('\n')) {
    if (/^```/.test(line.trim())) inFence = !inFence;
    if (inFence) continue;
    const m = /^(##|###)\s+(.+?)\s*#*\s*$/.exec(line);
    if (!m) continue;
    const text = plainHeadingText(m[2]);
    out.push({ depth: m[1] === '##' ? 2 : 3, text, id: slugifyHeading(text) });
  }
  return out;
}

function estimateReadingTime(content: string): number {
  // Strip JSX component tags so diagram props don't count as words.
  const prose = content.replace(/<[^>]+>/g, ' ');
  const words = prose.trim().split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(words / WORDS_PER_MINUTE));
}

function resolveHero(slug: string, category: CategoryKey, fm: BlogFrontmatter): string | null {
  // An explicit hero (e.g. a photograph in /assets/blog/photos) wins over the
  // generated art, which stays on disk as the fallback.
  if (fm.hero && fs.existsSync(path.join(PUBLIC_DIR, fm.hero))) return fm.hero;
  const conventional = `/assets/blog/${category}/${slug}.webp`;
  if (fs.existsSync(path.join(PUBLIC_DIR, conventional))) return conventional;
  return null;
}

/** Every .mdx slug on disk, regardless of status. */
function readSlugs(): string[] {
  return fs
    .readdirSync(BLOG_DIR)
    .filter((f) => f.endsWith('.mdx'))
    .map((f) => f.replace(/\.mdx$/, ''));
}

const cache = new Map<string, BlogPost>();

function readPost(slug: string): BlogPost {
  const hit = cache.get(slug);
  if (hit) return hit;
  const raw = fs.readFileSync(path.join(BLOG_DIR, `${slug}.mdx`), 'utf8');
  const { data, content } = matter(raw);
  const fm = data as BlogFrontmatter;
  const category = fm.category ?? 'astrology';
  const post: BlogPost = {
    slug,
    frontmatter: fm,
    category,
    status: fm.status ?? 'published',
    hero: resolveHero(slug, category, fm),
    content,
    readingTime: estimateReadingTime(content),
    headings: extractHeadings(content),
    isPillar: CATEGORIES[category].pillar === slug,
  };
  cache.set(slug, post);
  return post;
}

function isVisible(post: BlogPost): boolean {
  return post.status === 'published' || SHOW_REVIEW_CONTENT;
}

/**
 * `content/blog/*.mdx` is the only thing this module touches on disk — the
 * blog index, the post route, and sitemap.ts all import from here instead of
 * re-reading the directory themselves, so slugs stay in exactly one place.
 * Only slugs visible in this build are returned.
 */
export function getAllSlugs(): string[] {
  return readSlugs().filter((slug) => isVisible(readPost(slug)));
}

/** Throws if the slug doesn't exist or isn't visible in this build. */
export function getPost(slug: string): BlogPost {
  if (!/^[a-z0-9-]+$/.test(slug)) throw new Error(`Invalid slug: ${slug}`);
  const post = readPost(slug);
  if (!isVisible(post)) throw new Error(`Not published: ${slug}`);
  return post;
}

export function getAllPosts(): BlogPost[] {
  return getAllSlugs()
    .map(readPost)
    .sort((a, b) => (a.frontmatter.date < b.frontmatter.date ? 1 : a.frontmatter.date > b.frontmatter.date ? -1 : a.slug.localeCompare(b.slug)));
}

/** Only posts a production build would show — for sitemap, llms.txt, schema. */
export function getPublishedPosts(): BlogPost[] {
  return getAllPosts().filter((p) => p.status === 'published');
}

export function getPostsByCategory(category: CategoryKey): BlogPost[] {
  return getAllPosts().filter((p) => p.category === category);
}

/** Pillar first, then featured, then newest — the order hubs present a cluster in. */
export function getFeaturedPosts(category: CategoryKey, limit = 3): BlogPost[] {
  const posts = getPostsByCategory(category);
  const score = (p: BlogPost) => (p.isPillar ? 2 : 0) + (p.frontmatter.featured ? 1 : 0);
  return [...posts].sort((a, b) => score(b) - score(a)).slice(0, limit);
}

/** Every tag used across all posts, sorted alphabetically — backs the tag
 * archive pages at /blog/tag/[tag] and their generateStaticParams. */
export function getAllTags(): string[] {
  const tags = new Set<string>();
  for (const post of getAllPosts()) {
    for (const tag of post.frontmatter.tags ?? []) tags.add(tag);
  }
  return [...tags].sort((a, b) => a.localeCompare(b));
}

export function getPostsByTag(tag: string): BlogPost[] {
  return getAllPosts().filter((post) => post.frontmatter.tags?.includes(tag));
}

/**
 * Tag archives below this size are thin pages: still reachable (tags are
 * links on every post) but `noindex, follow` and left out of the sitemap.
 */
export const MIN_INDEXABLE_TAG_POSTS = 3;

/**
 * Related reading: hand-picked `related` slugs first, then the cluster's
 * pillar, then same-category posts scored by shared tags and shared
 * features. Cross-product links (Pooja room Vastu ↔ puja at home) only
 * happen through `related`, so they are always deliberate — an astrology
 * post never pads out with an unrelated puja guide.
 */
export function getRelatedPosts(post: BlogPost, limit = 4): BlogPost[] {
  const all = getAllPosts().filter((p) => p.slug !== post.slug);
  const bySlug = new Map(all.map((p) => [p.slug, p]));
  const picked: BlogPost[] = [];
  const add = (p: BlogPost | undefined) => {
    if (p && !picked.some((x) => x.slug === p.slug) && picked.length < limit) picked.push(p);
  };

  for (const slug of post.frontmatter.related ?? []) add(bySlug.get(slug));
  if (!post.isPillar) add(bySlug.get(CATEGORIES[post.category].pillar));

  const tagSet = new Set(post.frontmatter.tags ?? []);
  const featureSet = new Set(post.frontmatter.features ?? []);
  const scored = all
    .filter((p) => p.category === post.category)
    .map((p) => ({
      p,
      score:
        (p.frontmatter.tags ?? []).filter((t) => tagSet.has(t)).length * 2 +
        (p.frontmatter.features ?? []).filter((f) => featureSet.has(f)).length +
        // Posts that link to each other by hand are strongly related.
        ((p.frontmatter.related ?? []).includes(post.slug) ? 3 : 0),
    }))
    .sort((a, b) => b.score - a.score || (a.p.frontmatter.date < b.p.frontmatter.date ? 1 : -1));
  for (const { p } of scored) add(p);

  return picked;
}

/** True when the MDX body already has its own FAQ section, so the template
 * doesn't render the frontmatter FAQs a second time. */
export function bodyHasFaq(post: BlogPost): boolean {
  return post.headings.some((h) => /frequently asked|common questions|^faq/i.test(h.text));
}

export function formatDate(date: string): string {
  return new Date(`${date}T00:00:00Z`).toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'UTC',
  });
}

/**
 * MDX body with internal article links to slugs that aren't visible in this
 * build (e.g. still in review) turned into plain text, so publishing one
 * article before another it links to never ships a 404 link.
 */
export function renderableContent(post: BlogPost): string {
  const visible = new Set(getAllSlugs());
  const hubs = new Set(['astrology', 'vastu', 'puja', 'tag']);
  return post.content.replace(/\[([^\]]+)\]\(\/blog\/([a-z0-9-]+)(#[^)]*)?\)/g, (match, text: string, slug: string) =>
    visible.has(slug) || hubs.has(slug) ? match : text,
  );
}
