/**
 * Legal documents — Terms of Service, Privacy Policy, Astrology Disclaimer.
 *
 * The legal body is intentionally English-only: under Indian contract practice
 * a single governing-language text avoids enforceability disputes between
 * translations. Page chrome (titles, nav) is translated via i18n; a translated
 * banner on each page states that the English text governs. DPDP Act §5(3)
 * contemplates notices in Eighth Schedule languages — professionally reviewed
 * translations can be added later without changing this structure.
 *
 * LEGAL_VERSION is what every consent record is stamped with. Both consent
 * surfaces — onboarding and ConsentGate — import this constant rather than
 * restating the literal, because they had already drifted apart once (the
 * gate was writing "1.0.0" against documents that rendered "1.1.0", so every
 * record it wrote named a document nobody had been shown). AuthGuard also
 * compares the user's stored `termsVersion` against it, so bumping this
 * value re-prompts existing users instead of leaving them on stale consent.
 *
 * Legal entity (Aroha Astrology), registered office (Bangalore, India), and
 * the named Grievance Officer (Subir Dutta, subir@arohaastrology.in) are
 * filled in below. The whole text should be reviewed by qualified Indian
 * counsel — it is a considered draft, not legal advice.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * THIS FILE IS THE MIRROR — DO NOT EDIT IT DIRECTLY.
 *
 * The canonical copy is `frontend/lib/legal-content.ts`, which renders the
 * in-app /legal/* pages shown at the point of consent. This copy renders the
 * PUBLIC arohaastrology.in/legal/* pages — the URLs the Play Store listing
 * and the backend's GET /legal/current point at. They are separate git repos
 * with no shared CI, so nothing enforces the match: edit the frontend file
 * first, then copy it here verbatim and swap this header back in.
 * LEGAL_VERSION must also match jyotish-backend/src/modules/legal/legal.routes.ts.
 * ─────────────────────────────────────────────────────────────────────────
 */

export const LEGAL_VERSION = "1.3.0";
export const LEGAL_UPDATED = "7 August 2026";

export interface LegalSection {
  heading: string;
  paragraphs: string[];
}

export interface LegalDoc {
  slug: "terms" | "privacy" | "disclaimer";
  title: string;
  intro: string;
  sections: LegalSection[];
}

/* ────────────────────────────────────────────────────────────────────────── */
/* Terms of Service                                                           */
/* ────────────────────────────────────────────────────────────────────────── */

export const TERMS: LegalDoc = {
  slug: "terms",
  title: "Terms of Service",
  intro:
    "These Terms of Service (“Terms”) are an electronic record under the Information Technology Act, 2000 and the rules made thereunder, and constitute a legally binding agreement between you and Aroha Astrology, having its registered office at Bangalore, India (“Aroha”, “we”, “us”). By creating an account or using the Aroha Astrology application and services (the “Service”), you accept these Terms. This electronic record does not require a physical or digital signature (Section 10A, IT Act, 2000).",
  sections: [
    {
      heading: "1. Eligibility",
      paragraphs: [
        "You must be at least 18 years of age to use the Service. The Service processes personal data under consent; the Digital Personal Data Protection Act, 2023 (“DPDP Act”) requires verifiable parental consent for persons under 18, which the Service does not currently support. You confirm at sign-up that you are 18 or older, and the date of birth you enter is checked against that threshold — an account cannot be created for a person under 18.",
      ],
    },
    {
      heading: "2. Nature of the Service",
      paragraphs: [
        "Aroha provides Vedic astrology content — birth charts (kundli), panchang, horoscopes, compatibility matching, palm readings, and conversational readings by text or voice — computed from the birth details you provide and, in part, generated by artificial-intelligence systems.",
        "Astrology is a traditional belief system. The Service is offered for spiritual, cultural, and informational guidance only. It is not a scientific instrument, and nothing in the Service is a prediction, promise, or guarantee of any outcome, event, or result.",
      ],
    },
    {
      heading: "3. No Professional Advice",
      paragraphs: [
        "Content from the Service (including AI chat responses, horoscopes, remedies, and match reports) is not medical, psychological, legal, financial, or investment advice, and must not be used as a substitute for consultation with qualified professionals. Never disregard professional advice or delay seeking it because of anything read on the Service.",
        "Suggested remedies (gemstones, rituals, mantras, and similar) are traditional practices shared for cultural and spiritual interest. We make no claim — and you should infer none — that any remedy cures, treats, or prevents any disease or condition, or produces any material outcome. We do not make claims of the kind restricted by the Drugs and Magic Remedies (Objectionable Advertisements) Act, 1954.",
      ],
    },
    {
      heading: "4. AI-Generated Content",
      paragraphs: [
        "Parts of the Service are generated by AI language models grounded in your computed chart. AI output can be incomplete, imprecise, or wrong, and may vary between sessions. It reflects astrological interpretation, not verified fact, and is provided “as is”.",
      ],
    },
    {
      heading: "5. Your Account and Responsibilities",
      paragraphs: [
        "You agree to provide accurate birth details — readings are computed directly from them — and to keep your phone number and OTPs secure. You are responsible for activity under your account.",
        "You agree not to misuse the Service: no unlawful, defamatory, or infringing content; no attempts to probe, overload, reverse-engineer, or disrupt the Service; no scraping or bulk extraction; no impersonation.",
      ],
    },
    {
      heading: "6. Birth Details of Other Persons",
      paragraphs: [
        "Features such as compatibility matching let you submit another person's name and birth details. You must do so only with that person's knowledge and consent (or, for a minor, their guardian's consent). You confirm you are authorised to share such details, and you indemnify us against claims arising from details you were not entitled to share.",
      ],
    },
    {
      heading: "7. Payments and Refunds",
      paragraphs: [
        "Parts of the Service may be offered for a fee. Prices, inclusions, and billing terms are shown before purchase. Except where required by law (including the Consumer Protection Act, 2019 and the Consumer Protection (E-Commerce) Rules, 2020), fees for digital content already delivered are non-refundable. Statutory rights you hold as a consumer under Indian law are not affected by these Terms.",
      ],
    },
    {
      heading: "8. Intellectual Property",
      paragraphs: [
        "The Service — including software, design, text, charts, and branding — is owned by or licensed to Aroha and protected under Indian copyright and trademark law. We grant you a personal, non-exclusive, non-transferable licence to use the Service for personal, non-commercial purposes. Your birth details remain yours; you grant us the licence needed to process them to provide the Service, as described in the Privacy Policy.",
      ],
    },
    {
      heading: "9. Suspension and Termination",
      paragraphs: [
        "We may suspend or terminate access for breach of these Terms, unlawful use, or risk to the Service or other users. You may stop using the Service and delete your account at any time from within the app; deletion is handled as described in the Privacy Policy.",
      ],
    },
    {
      heading: "10. Limitation of Liability",
      paragraphs: [
        "To the maximum extent permitted by Indian law, Aroha shall not be liable for indirect, incidental, or consequential loss, or for decisions taken in reliance on astrological or AI-generated content. Our total aggregate liability for any claim relating to the Service shall not exceed the amount you paid us in the six months preceding the claim (or ₹1,000 if you paid nothing). Nothing in these Terms limits liability that cannot be limited under Indian law.",
      ],
    },
    {
      heading: "11. Privacy",
      paragraphs: [
        "Personal data is processed as described in the Privacy Policy, which forms part of these Terms and reflects our obligations under the DPDP Act, 2023 and the IT Act, 2000 (including the SPDI Rules, 2011).",
      ],
    },
    {
      heading: "12. Changes to These Terms",
      paragraphs: [
        "We may revise these Terms. Material changes will be notified in the app, and the version number and date above will change. Continued use after the effective date constitutes acceptance; if you do not agree, stop using the Service and delete your account.",
      ],
    },
    {
      heading: "13. Governing Law and Jurisdiction",
      paragraphs: [
        "These Terms are governed by the laws of India. Subject to any mandatory consumer-protection forum available to you, the courts at Bangalore, Karnataka, India shall have exclusive jurisdiction.",
      ],
    },
    {
      heading: "14. Grievance Redressal",
      paragraphs: [
        "Grievance Officer: Subir Dutta, Aroha Astrology, Bengaluru, Karnataka, India. Email: subir@arohaastrology.in. We acknowledge every grievance within 24 hours of receipt and endeavour to resolve it within 15 days, as required by Rule 3(2)(a) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, and consistent with the DPDP Act, 2023.",
      ],
    },
  ],
};

/* ────────────────────────────────────────────────────────────────────────── */
/* Privacy Policy                                                             */
/* ────────────────────────────────────────────────────────────────────────── */

export const PRIVACY: LegalDoc = {
  slug: "privacy",
  title: "Privacy Policy",
  intro:
    "This Privacy Policy is the notice required under Section 5 of the Digital Personal Data Protection Act, 2023 (“DPDP Act”). Aroha Astrology, registered office Bangalore, India, is the Data Fiduciary for personal data processed through the Aroha Astrology application (the “Service”). It also reflects reasonable security practices under Section 43A of the IT Act, 2000 and the SPDI Rules, 2011.",
  sections: [
    {
      heading: "1. Personal Data We Collect",
      paragraphs: [
        "Account data: mobile phone number (verified by OTP), display name, gender.",
        "Birth data: date of birth, exact time of birth, place of birth including geographic coordinates and timezone. Because readings are computed from it, this is the core data the Service needs.",
        "Third-party birth profiles: name and birth details of another person that you submit for compatibility matching — only to be provided with that person's consent.",
        "Device location: if you grant the location permission, we collect your device's approximate location — city-level only; we never request high-accuracy or background location, and we do not track your movements. It is used while the app is open, and the location recorded at onboarding is stored on your profile as your current location until you delete your account. This is separate from your place of birth, which you enter yourself. Location is optional: you may decline the permission, or revoke it later in your device settings, and the Service continues to work — location-aware features such as local panchang timings simply fall back to a default reference location.",
        "Palm photographs (biometric data): if you use Palm Reading, we collect the photographs of your palms that you capture with the camera or upload. Palm images are biometric data and are treated as our most sensitive category. They are stored on our servers, are never publicly accessible — every read is authenticated and ownership-checked — and are used solely to generate your palm reading. They are permanently deleted, not merely deactivated, the moment you delete your account. Palm Reading is optional; if you never open it, no photograph is ever collected.",
        "Voice recordings: if you use Voice Chat, your microphone audio is streamed in real time to our AI inference provider so the AI astrologer can hear and answer you. The audio is processed for the duration of the call to produce a response and is not retained by us as a recording afterwards; the resulting conversation is stored as text in the same way a typed chat is. Voice Chat is optional, is off unless you enable it, and requires a separate microphone consent in addition to the consent described in Section 3.",
        "Usage data: chat messages you send to the AI astrologer, feature usage, preferences (language, ayanamsa, house system), and technical logs (device type, approximate region, timestamps).",
      ],
    },
    {
      heading: "2. Purposes of Processing",
      paragraphs: [
        "We process personal data to: compute your kundli, dasha, panchang, and horoscopes; generate personalised AI readings and chat responses; run compatibility matching you request; read the palms you photograph; hold spoken conversations with you in Voice Chat; operate, secure, and debug the Service; send service notifications you opt into; and meet legal obligations. We do not sell personal data, and we do not use it for third-party advertising.",
        "Palm photographs are used for one purpose only — producing the palm reading you asked for. We do not use them for identification, verification, matching against any other person, or training AI models, and we do not share them with anyone outside the AI inference provider that generates the reading itself.",
        "Device location, where you grant it, is used only to localise time-sensitive astrological calculations — panchang timings, sunrise and sunset, and transit readings are all specific to where you are — and to name that place back to you in the interface. We do not use location for advertising, profiling, or tracking, and we do not share it with data brokers.",
      ],
    },
    {
      heading: "3. Legal Basis — Your Consent",
      paragraphs: [
        "We process your personal data on the basis of consent (Section 6, DPDP Act), collected at onboarding through a free, specific, informed, and unambiguous affirmative action. You may withdraw consent at any time in Settings or by deleting your account; withdrawal stops future processing but does not affect processing already carried out. Some features (chart, horoscope, chat, matching) cannot function without the birth data they compute from — withdrawing consent for that data means those features stop working.",
      ],
    },
    {
      heading: "4. How Processing Works",
      paragraphs: [
        "Chart mathematics run on our servers using astronomical (ephemeris) calculations. Narrative content is generated by AI language models that receive your computed chart context (and your chat messages) to produce a response. Consent events are recorded in an append-only audit log with timestamps and document versions, as the DPDP Act's accountability provisions contemplate.",
      ],
    },
    {
      heading: "5. Sharing and Data Processors",
      paragraphs: [
        "We share personal data only with processors who operate the Service under contract and on our instructions: cloud hosting and database providers, Google Firebase (phone authentication), and AI inference providers that process chart context and chat text to generate responses. Processors are not permitted to use your data for their own purposes.",
        "Two of those flows are worth stating plainly because they involve the most sensitive categories. Palm photographs are transmitted to our AI inference provider to be interpreted into a reading. Voice Chat audio is streamed to that provider in real time for the duration of a call so it can respond in speech. In both cases the provider acts on our instructions to answer your request, and is not permitted to use the images or audio for its own purposes, including model training.",
        "One exception is disclosed for completeness: when you grant location, your coordinates are sent to the OpenStreetMap Nominatim service to convert them into a place name for display. That is a public lookup service used without an account, not a contracted processor, and it receives coordinates only — never your identity, phone number, or birth details.",
        "Some processors may store or process data outside India. Such transfers are made in accordance with Section 16 of the DPDP Act (which permits transfers except to countries restricted by the Central Government) and with contractual safeguards.",
        "We may disclose personal data where required by Indian law or lawful government request.",
      ],
    },
    {
      heading: "6. Retention and Deletion",
      paragraphs: [
        "We retain personal data while your account is active. Deleting your account in the app (Settings → Delete Account) submits a deletion request, which we review before acting on it — normally within three to seven business days. We do this so that an irreversible erasure is never triggered by a mis-tap, and we will tell you on screen that the request has been received. Your account continues to work during the review, though we stop sending you notifications and stop generating new readings for you from the moment you ask.",
        "Once the request is approved the erasure itself is irreversible and is not merely a flag: your name, gender, email, date, time and place of birth, gotra, current location, relationship status and every other identifying field on your profile — and the same fields on any third-party birth profile you created — are overwritten outright.",
        "Your palm photographs, chat transcripts, saved AI memory, and feedback are the highest-risk categories, so they are permanently destroyed outright rather than overwritten in place. Push notification tokens for your devices are revoked and scrubbed.",
        "Two things are deliberately retained, and we would rather state them than imply a completeness we do not deliver. First, your mobile number and authentication identifier are kept on the emptied account shell. This is a security and anti-abuse measure, not a use of your data. It serves two purposes: mobile numbers in India are recycled to new subscribers, and keeping the shell is what guarantees that whoever is issued your number next receives a blank, freshly-onboardable account instead of inheriting anything of yours; and because new accounts receive a one-time sign-up credit, retaining the number is what stops the same person from claiming that credit repeatedly by deleting and re-registering. If you sign in again on that number you return to the same emptied account — we will say so, and you will need to enter your details afresh. Nothing of substance remains attached to it. Second, the consent audit log keeps a skeleton record — which consent, which document version, and when — because the DPDP Act's accountability provisions require us to be able to evidence the lawful basis on which we processed data; the IP address and device string on those records are scrubbed with everything else.",
        "Payment and tax records are retained for the period Indian law requires. Backup copies purge on their own rotation cycle. If you want the retained shell and consent skeleton removed as well, write to the Grievance Officer in Section 10 and we will action it manually.",
      ],
    },
    {
      heading: "7. Your Rights (DPDP Act, Sections 11–14)",
      paragraphs: [
        "You have the right to: access a summary of your personal data and the processing done on it — Settings → Download My Data exports everything we hold on you as a machine-readable file, at any time and without asking us; correct and update it (your profile is editable in the app); erase it (delete your account, or write to us); a readily available grievance mechanism (Section 10 above); and nominate another individual to exercise your rights if you die or are incapacitated.",
        "You also have duties under Section 15 of the DPDP Act, including not to impersonate another person or suppress material information when providing data.",
      ],
    },
    {
      heading: "8. Children",
      paragraphs: [
        "The Service is for users 18 and over. We do not knowingly process the personal data of children as defined by the DPDP Act. If you believe a minor has created an account, contact the Grievance Officer and we will delete it.",
      ],
    },
    {
      heading: "9. Security",
      paragraphs: [
        "We follow reasonable security practices under Section 43A of the IT Act, 2000: encryption in transit (TLS), AES-256 encryption at rest for the most sensitive fields — birth details, gotra, and chat transcripts — access controls, authenticated APIs, and audit logging. Palm photographs are never publicly addressable and are served only through an authenticated, ownership-checked route. No system is perfectly secure; in the event of a personal data breach we will notify the Data Protection Board of India and affected users as required by Section 8(6) of the DPDP Act.",
      ],
    },
    {
      heading: "10. Grievances and the Data Protection Board",
      paragraphs: [
        "Grievance Officer (also our contact point for all data-protection questions): Subir Dutta. Email: subir@arohaastrology.in. Address: Aroha Astrology, Bengaluru, Karnataka, India.",
        "We acknowledge every grievance within 24 hours of receipt and endeavour to resolve it within 15 days, as required by Rule 3(2)(a) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021. Use the same address to exercise any right in Section 7, including erasure of retained records described in Section 6.",
        "Aroha has not been notified as a Significant Data Fiduciary under Section 10 of the DPDP Act and is therefore not required to appoint a statutory Data Protection Officer; the Grievance Officer above performs that contact function. If that notification status changes, this Section will be updated and a DPO named.",
        "If you are unsatisfied after exhausting this mechanism, you may complain to the Data Protection Board of India under the DPDP Act.",
      ],
    },
    {
      heading: "11. Changes to This Policy",
      paragraphs: [
        "We may update this Policy. Material changes will be notified in the app; where the change expands the purposes of processing, we will seek fresh consent as the DPDP Act requires. The version and date above always reflect the current text.",
      ],
    },
  ],
};

/* ────────────────────────────────────────────────────────────────────────── */
/* Astrology & AI Disclaimer                                                  */
/* ────────────────────────────────────────────────────────────────────────── */

export const DISCLAIMER: LegalDoc = {
  slug: "disclaimer",
  title: "Astrology & AI Disclaimer",
  intro:
    "This disclaimer applies to all content in the Aroha Astrology application — charts, horoscopes, panchang, compatibility reports, palm readings, remedies, and AI astrologer conversations by text or voice.",
  sections: [
    {
      heading: "1. Astrology Is a Belief System",
      paragraphs: [
        "Vedic astrology is a traditional practice and system of belief. Its content is offered for spiritual, cultural, and informational purposes. It is not science, and no reading is a prediction, promise, or guarantee of any event, outcome, or result.",
        "The same applies to palmistry. A palm reading is a traditional interpretation of the lines and features in a photograph, not a measurement, a diagnosis, or an identification. It tells you nothing verifiable about your health, your lifespan, or your future, and we make no claim that it does.",
      ],
    },
    {
      heading: "2. Not Professional Advice",
      paragraphs: [
        "Nothing in the Service is medical, psychological, legal, financial, investment, or other professional advice. Decisions about health, money, relationships, career, or legal matters should be made with qualified professionals. Never disregard or delay professional advice because of a reading.",
      ],
    },
    {
      heading: "3. Remedies",
      paragraphs: [
        "Gemstones, rituals, mantras, and other suggested remedies are traditional practices shared for cultural interest. They are not treatments and are not claimed to cure, prevent, or mitigate any disease or condition (Drugs and Magic Remedies (Objectionable Advertisements) Act, 1954), nor to produce any material result. Consult a doctor for health concerns.",
      ],
    },
    {
      heading: "4. AI-Generated Content",
      paragraphs: [
        "AI responses are generated by language models interpreting your computed chart. They can be wrong, incomplete, or inconsistent, and do not represent the views of any human astrologer. Use your own judgment.",
      ],
    },
    {
      heading: "5. Personal Responsibility",
      paragraphs: [
        "You remain solely responsible for decisions and actions taken after using the Service. To the maximum extent permitted by Indian law, Aroha accepts no liability for reliance placed on astrological or AI-generated content.",
      ],
    },
  ],
};

export const LEGAL_DOCS: Record<LegalDoc["slug"], LegalDoc> = {
  terms: TERMS,
  privacy: PRIVACY,
  disclaimer: DISCLAIMER,
};
