#!/usr/bin/env node
// Turns translated markdown files into the JSON the site loads.
//
//   npm run i18n:import            every i18n/<code>.md that exists
//   npm run i18n:import -- hi de   only those languages
//   add --partial to write a language even if some strings are missing
//
// A language is written only when it covers every string in en.md, so the
// switcher never offers a half-translated language.
import fs from 'node:fs';
import path from 'node:path';
import { I18N_DIR, LANGUAGES, ROOT, readStringsFile } from './lib.mjs';

const OUT = path.join(ROOT, 'src/lib/i18n/locales');
const args = process.argv.slice(2);
const partial = args.includes('--partial');
const wanted = args.filter((a) => !a.startsWith('--'));
const codes = wanted.length ? wanted : LANGUAGES;

const enFile = path.join(I18N_DIR, 'en.md');
if (!fs.existsSync(enFile)) throw new Error('i18n/en.md not found. Run `npm run build && npm run i18n:export` first.');
const en = readStringsFile(enFile);

fs.mkdirSync(OUT, { recursive: true });
let failed = false;

for (const code of codes) {
  if (!LANGUAGES.includes(code)) {
    console.log(`${code}: not one of ${LANGUAGES.join(', ')}`);
    failed = true;
    continue;
  }
  const file = path.join(I18N_DIR, `${code}.md`);
  if (!fs.existsSync(file)) continue;

  const tr = readStringsFile(file);
  const missing = [...en.keys()].filter((id) => !tr.get(id));
  const unknown = [...tr.keys()].filter((id) => !en.has(id));
  const dashes = [...tr].filter(([, text]) => /[—–]/.test(text)).map(([id]) => id);
  const english = [...tr].filter(([id, text]) => en.get(id) === text && text.length > 24).map(([id]) => id);

  console.log(`${code}: ${tr.size - unknown.length}/${en.size} translated`);
  if (missing.length) console.log(`  missing ${missing.length}: ${missing.slice(0, 6).join(' ')}${missing.length > 6 ? ' …' : ''}`);
  if (unknown.length) console.log(`  unknown ids ${unknown.length}: ${unknown.slice(0, 6).join(' ')}`);
  if (english.length) console.log(`  ${english.length} long strings still identical to English: ${english.slice(0, 4).join(' ')}${english.length > 4 ? ' …' : ''}`);
  if (dashes.length) console.log(`  ${dashes.length} contain a dash: ${dashes.slice(0, 4).join(' ')}`);

  if (missing.length && !partial) {
    console.log('  not written (use --partial to write anyway)');
    failed = true;
    continue;
  }
  const map = {};
  for (const [id, source] of en) if (tr.get(id)) map[source] = tr.get(id);
  fs.writeFileSync(path.join(OUT, `${code}.json`), `${JSON.stringify(map, null, 1)}\n`);
  console.log(`  wrote src/lib/i18n/locales/${code}.json`);
}

// Loader table, so the bundler knows every locale file and each loads on demand.
const present = LANGUAGES.filter((c) => fs.existsSync(path.join(OUT, `${c}.json`)));
const index = [
  '// Generated by scripts/i18n/import.mjs. Do not edit.',
  'export const LOCALE_LOADERS: Record<string, () => Promise<Record<string, string>>> = {',
  ...present.map((c) => `  ${c}: () => import('./${c}.json').then((m) => m.default),`),
  '};',
  '',
].join('\n');
fs.writeFileSync(path.join(OUT, 'index.ts'), index);
console.log(`Languages available on the site: ${present.length ? present.join(', ') : 'none yet'}`);
process.exit(failed ? 1 : 0);
