// Generated by scripts/i18n/import.mjs. Do not edit.
export const LOCALE_LOADERS: Record<string, () => Promise<Record<string, string>>> = {
  hi: () => import('./hi.json').then((m) => m.default),
  bn: () => import('./bn.json').then((m) => m.default),
  ta: () => import('./ta.json').then((m) => m.default),
  te: () => import('./te.json').then((m) => m.default),
  mr: () => import('./mr.json').then((m) => m.default),
  gu: () => import('./gu.json').then((m) => m.default),
  kn: () => import('./kn.json').then((m) => m.default),
  es: () => import('./es.json').then((m) => m.default),
  fr: () => import('./fr.json').then((m) => m.default),
  de: () => import('./de.json').then((m) => m.default),
  pt: () => import('./pt.json').then((m) => m.default),
  it: () => import('./it.json').then((m) => m.default),
  ru: () => import('./ru.json').then((m) => m.default),
  ja: () => import('./ja.json').then((m) => m.default),
};
