const FLOW = [
  { k: 'Your question', v: 'Anything, in your own words and language: work, relationships, timing, a placement you don’t understand.' },
  { k: 'Your chart as context', v: 'Your Lagna, the Dasha you’re running and today’s transits, all computed from your own birth details.' },
  { k: 'Aroha’s Vedic Astrologer', v: 'Reads the question against classical rules and your chart.' },
  { k: 'A personal interpretation', v: 'Plain-language guidance with the reasoning shown, so you can weigh it for yourself.' },
];

/**
 * How chart-grounded answers work. Honest by construction: it says the
 * answers are AI-generated and that astrology is interpretation, not
 * prediction. It is the same disclosure /about makes.
 */
export function AskSection() {
  return (
    <section id="ask" aria-labelledby="ask-title" className="scroll-mt-20 bg-paper px-[clamp(20px,4vw,56px)] py-[clamp(72px,9vw,128px)]">
      <div className="mx-auto max-w-[1280px]">
        <div className="reveal max-w-3xl">
          <p className="j-eyebrow text-[13px]">Ask about your own chart</p>
          <h2 id="ask-title" className="font-display mt-3 text-[clamp(34px,4.6vw,58px)] font-medium leading-[1.05] text-balance">
            Answers that start from your own chart
          </h2>
          <p className="mt-6 text-lg leading-relaxed text-ink-2">
            The Vedic Astrologer chat in Aroha Astrology answers from what is in your Kundli. Use it to understand your own chart.
          </p>
        </div>

        <ol className="mt-14 grid gap-4 md:grid-cols-4">
          {FLOW.map((step, i) => (
            <li key={step.k} className="reveal relative rounded-3xl border border-rule bg-paper-raised p-6" style={{ ['--reveal-i' as string]: i }}>
              <span className="flex h-9 w-9 items-center justify-center rounded-full border border-accent font-display text-accent-text">{i + 1}</span>
              <h3 className="font-display mt-5 text-xl text-ink">{step.k}</h3>
              <p className="mt-2 text-[14.5px] leading-relaxed text-ink-2">{step.v}</p>
              {i < FLOW.length - 1 && (
                <span aria-hidden className="absolute -right-3 top-10 z-10 hidden h-6 w-6 items-center justify-center rounded-full border border-rule bg-paper text-xs text-accent-text md:flex">
                  →
                </span>
              )}
            </li>
          ))}
        </ol>

        <div className="mt-12 grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,420px)]">
          <figure className="reveal rounded-3xl border border-rule bg-paper-sunk p-6 sm:p-8">
            <figcaption className="text-xs font-semibold uppercase tracking-[0.14em] text-ink-muted">Illustrative exchange</figcaption>
            <div className="mt-5 space-y-4 text-[15px] leading-relaxed">
              <p className="ml-auto max-w-[85%] rounded-2xl rounded-br-md bg-ink px-4 py-3 text-paper">
                I’m running Jupiter Mahadasha. Is this a reasonable time to go back to studying?
              </p>
              <p className="max-w-[92%] rounded-2xl rounded-bl-md border border-rule bg-paper-raised px-4 py-3 text-ink-2">
                In your chart Jupiter rules the 9th house, traditionally the house of higher learning, and sits in the 5th, the house of
                intellect. Classical texts read that combination as supportive of study during Jupiter’s period. Your Saturn Antardasha
                begins next year, which is usually read as slower, steadier progress rather than a block.
              </p>
            </div>
          </figure>
          <aside className="reveal flex flex-col justify-center rounded-3xl bg-ink p-7 text-paper" style={{ ['--reveal-i' as string]: 1 }}>
            <p className="font-display text-2xl">What it is</p>
            <p className="mt-3 text-[14.5px] leading-relaxed text-night-ink-2">
              Chart positions are computed astronomically. The written answers are generated by AI from your computed chart and classical
              Vedic texts, and no human astrologer reviews each one. Vedic astrology is a tradition of interpretation, and it does not
              predict the future scientifically. Use it for reflection, and ask a professional about medical, legal or financial decisions.
            </p>
          </aside>
        </div>
      </div>
    </section>
  );
}
